version: '3'

volumes:
    data:

services:
  db:
    image: postgres:9.6
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpass
      POSTGRES_DB: pgdb
    ports:
      - 5591:5432
    volumes:
      - data:/var/lib/postgresql/data

  rabbit:
    image: rabbitmq:3.6
    environment:
      RABBITMQ_DEFAULT_USER: rabuser
      RABBITMQ_DEFAULT_PASS: rabpass
      RABBITMQ_DEFAULT_VHOST: recarguide
    ports:
      - 5592:5672
      - 5593:15672

  celery:
    build: ./backend
    command: make celery
    volumes:
      - ./backend/:/opt/recarguide/backend/
    depends_on:
      - db
      - rabbit

  backend:
    build: ./backend
    command: make web
    volumes:
      - ./backend/:/opt/recarguide/backend/
    ports:
      - 5590:8080
    depends_on:
      - db
      - rabbit

  frontend:
    image: node:8
    working_dir: /opt/recarguide/frontend/
    command: make webpack
    volumes:
      - ./frontend/:/opt/recarguide/frontend/
