version: '3'

volumes:
    pg_data:
      driver: local
    elastic_data:
      driver: local

services:
  pg:
    image: postgres:9.6
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpass
      POSTGRES_DB: pgdb
    ports:
      - 5591:5432
    volumes:
      - pg_data:/var/lib/postgresql/data

  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.5
    environment:
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elastic_data:/usr/share/elasticsearch/data
    ports:
      - 5594:9200

  rabbit:
    image: rabbitmq:3.6
    environment:
      RABBITMQ_DEFAULT_USER: rabuser
      RABBITMQ_DEFAULT_PASS: rabpass
      RABBITMQ_DEFAULT_VHOST: recarguide
    ports:
      - 5592:5672
      - 5593:15672

  celery:
    build: ./backend
    command: celery worker --app recarguide --loglevel INFO
    volumes:
      - ./backend/:/opt/recarguide/backend/
    depends_on:
      - pg
      - elastic
      - rabbit

  flower:
    build: ./backend
    command: flower -A recarguide --port=8081
    volumes:
      - ./backend/:/opt/recarguide/backend/
    depends_on:
      - celery
    ports:
      - 5595:8081

  backend:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8080
    volumes:
      - ./backend/:/opt/recarguide/backend/
      - ./frontend/dist/:/opt/recarguide/backend/common/static/
    ports:
      - 5590:8080
    depends_on:
      - pg
      - elastic
      - celery
      - frontend

  frontend:
    image: node:8
    working_dir: /opt/recarguide/frontend/
    command: yarn install && node_modules/.bin/webpack --watch
    volumes:
      - ./frontend/:/opt/recarguide/frontend/
