# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-12 07:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(default='', max_length=250)),
                ('slug', models.SlugField(default='', max_length=250)),
                ('price', models.PositiveIntegerField(default=0)),
                ('year', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('slug', models.SlugField(default='')),
                ('parent', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='cars.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Make',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('slug', models.SlugField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('slug', models.SlugField(default='')),
                ('make', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cars.Make')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='cars.Category'),
        ),
        migrations.AddField(
            model_name='car',
            name='make',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='cars.Make'),
        ),
        migrations.AddField(
            model_name='car',
            name='model',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='cars.Model'),
        ),
    ]
