# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-13 08:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='name',
            field=models.CharField(default='', max_length=250),
        ),
    ]
