# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-15 06:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('cars', '0002_auto_20171013_0843'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='description',
            field=models.TextField(default='', max_length=10000),
        ),
        migrations.AddField(
            model_name='car',
            name='mileage',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
