# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-18 10:53
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('sale', '0010_auto_20171016_2219'),
        ('cars', '0003_auto_20171015_0621'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('ready', models.BooleanField(default=False)),
                ('uid', models.CharField(max_length=16)),
                ('filename', models.CharField(max_length=250)),
                ('filedata', models.TextField(default=None, null=True)),
                ('car', models.ForeignKey(default=None, null=True,
                                          on_delete=django.db.models.deletion.PROTECT,
                                          to='cars.Car')),
                ('sell_process', models.ForeignKey(default=None,
                                                   on_delete=django.db.models.deletion.PROTECT,
                                                   to='sale.SellProcess')),
            ],
        ),
    ]
