# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-04 10:58
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('cars', '0005_photo_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='car',
            field=models.ForeignKey(default=None, null=True,
                                    on_delete=django.db.models.deletion.PROTECT,
                                    related_name='photos', to='cars.Car'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='sell_process',
            field=models.ForeignKey(default=None,
                                    on_delete=django.db.models.deletion.PROTECT,
                                    related_name='photos',
                                    to='sale.SellProcess'),
        ),
    ]
