# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-18 09:26
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('cars', '0007_auto_20171118_1400'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('slug', models.SlugField(default='')),
                ('make', models.ForeignKey(default=None,
                                           on_delete=django.db.models.deletion.CASCADE,
                                           to='cars.Make')),
                ('model', models.ForeignKey(default=None,
                                            on_delete=django.db.models.deletion.CASCADE,
                                            to='cars.Model')),
            ],
        ),
    ]
