# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-18 11:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0009_auto_20171118_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='trim',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='cars.Trim'),
        ),
    ]
