# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-18 12:37
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('cars', '0010_car_trim'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='trim_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='car',
            name='trim',
            field=models.ForeignKey(default=None, null=True,
                                    on_delete=django.db.models.deletion.PROTECT,
                                    to='cars.Trim'),
        ),
    ]
