# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-07 18:01
from __future__ import unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('cars', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sale', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='sell_process',
            field=models.ForeignKey(default=None,
                                    on_delete=django.db.models.deletion.PROTECT,
                                    related_name='photos',
                                    to='sale.SellProcess'),
        ),
        migrations.AddField(
            model_name='photo',
            name='user',
            field=models.ForeignKey(default=None,
                                    on_delete=django.db.models.deletion.PROTECT,
                                    to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='model',
            name='make',
            field=models.ForeignKey(default=None,
                                    on_delete=django.db.models.deletion.CASCADE,
                                    to='cars.Make'),
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(default=None, null=True,
                                    on_delete=django.db.models.deletion.CASCADE,
                                    to='cars.Category'),
        ),
        migrations.AddField(
            model_name='car',
            name='category',
            field=models.ForeignKey(default=None,
                                    on_delete=django.db.models.deletion.PROTECT,
                                    to='cars.Category'),
        ),
        migrations.AddField(
            model_name='car',
            name='make',
            field=models.ForeignKey(default=None,
                                    on_delete=django.db.models.deletion.PROTECT,
                                    to='cars.Make'),
        ),
        migrations.AddField(
            model_name='car',
            name='model',
            field=models.ForeignKey(default=None,
                                    on_delete=django.db.models.deletion.PROTECT,
                                    to='cars.Model'),
        ),
        migrations.AddField(
            model_name='car',
            name='trim',
            field=models.ForeignKey(default=None, null=True,
                                    on_delete=django.db.models.deletion.PROTECT,
                                    to='cars.Trim'),
        ),
    ]
