# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-13 10:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('sale', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='packageplan',
            old_name='max_listings',
            new_name='featured_days',
        ),
    ]
