# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-13 11:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0003_packageplan_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='packageplan',
            name='description',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='packageplan',
            name='primary',
            field=models.BooleanField(default=False),
        ),
    ]
