# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-13 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('sale', '0004_auto_20171013_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellprocess',
            name='step',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
