# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-13 14:52
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('sale', '0005_sellprocess_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellprocess',
            name='package_plan',
            field=models.ForeignKey(default=None, null=True,
                                    on_delete=django.db.models.deletion.PROTECT,
                                    to='sale.PackagePlan'),
        ),
    ]
