# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-15 16:17
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('sale', '0006_sellprocess_package_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=50)),
                ('last_name', models.CharField(default='', max_length=50)),
                ('address', models.CharField(default='', max_length=75)),
                ('address2', models.CharField(default='', max_length=75)),
                ('city', models.CharField(default='', max_length=75)),
                ('country', models.CharField(default='', max_length=2)),
                ('phone', models.CharField(default='', max_length=25)),
                ('contact_method', models.CharField(default='', max_length=1)),
                ('sell_process', models.ForeignKey(default=None,
                                                   on_delete=django.db.models.deletion.PROTECT,
                                                   to='sale.SellProcess')),
            ],
        ),
    ]
