# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-15 16:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('sale', '0007_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='zip',
            field=models.CharField(default='', max_length=10),
        ),
    ]
