# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-16 13:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('sale', '0008_contact_zip'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellprocess',
            name='finished',
            field=models.BooleanField(default=False),
        ),
    ]
