# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-16 16:19
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('sale', '0009_sellprocess_finished'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellprocess',
            name='payment',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=None,
                                                                 null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='sell_process',
            field=models.ForeignKey(default=None,
                                    on_delete=django.db.models.deletion.PROTECT,
                                    related_name='contacts',
                                    to='sale.SellProcess'),
        ),
    ]
