# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-04 10:58
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('sale', '0010_auto_20171016_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='sell_process',
            field=models.OneToOneField(default=None,
                                       on_delete=django.db.models.deletion.PROTECT,
                                       related_name='contact',
                                       to='sale.SellProcess'),
        ),
        migrations.AlterField(
            model_name='sellprocess',
            name='car',
            field=models.OneToOneField(default=None, null=True,
                                       on_delete=django.db.models.deletion.PROTECT,
                                       to='cars.Car'),
        ),
    ]
