# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-04 11:01
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('cars', '0006_auto_20171104_1658'),
        ('sale', '0011_auto_20171104_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='car',
            field=models.OneToOneField(default=None, null=True,
                                       on_delete=django.db.models.deletion.PROTECT,
                                       related_name='contact', to='cars.Car'),
        ),
    ]
