# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-07 18:01
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=50)),
                ('last_name', models.CharField(default='', max_length=50)),
                ('address', models.CharField(default='', max_length=75)),
                ('address2', models.CharField(default='', max_length=75)),
                ('city', models.CharField(default='', max_length=75)),
                ('country', models.CharField(default='', max_length=2)),
                ('zip', models.CharField(default='', max_length=10)),
                ('phone', models.CharField(default='', max_length=25)),
                ('contact_method', models.CharField(default='', max_length=1)),
                ('car', models.OneToOneField(default=None, null=True,
                                             on_delete=django.db.models.deletion.PROTECT,
                                             related_name='contact',
                                             to='cars.Car')),
            ],
        ),
        migrations.CreateModel(
            name='PackagePlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('slug', models.SlugField(default='')),
                ('price', models.PositiveIntegerField(default=0)),
                ('featured_days', models.PositiveSmallIntegerField(default=0)),
                ('max_photos', models.PositiveSmallIntegerField(default=0)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('primary', models.BooleanField(default=False)),
                ('description', models.CharField(default='', max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='SellProcess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('step', models.PositiveSmallIntegerField(default=1)),
                ('finished', models.BooleanField(default=False)),
                ('payment',
                 django.contrib.postgres.fields.jsonb.JSONField(default=None,
                                                                null=True)),
                ('car', models.OneToOneField(default=None, null=True,
                                             on_delete=django.db.models.deletion.PROTECT,
                                             to='cars.Car')),
                ('package_plan', models.ForeignKey(default=None, null=True,
                                                   on_delete=django.db.models.deletion.PROTECT,
                                                   to='sale.PackagePlan')),
                ('user', models.ForeignKey(default=None,
                                           on_delete=django.db.models.deletion.PROTECT,
                                           to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='contact',
            name='sell_process',
            field=models.OneToOneField(default=None,
                                       on_delete=django.db.models.deletion.PROTECT,
                                       related_name='contact',
                                       to='sale.SellProcess'),
        ),
    ]
